# values for portfolio production environment


sealedSecrets:
  encryptionNS: portfolio-prod
  tls:
    secretName: cloudflare-tls
    crt: AgAg4uHwRxQKUJA7uqSsZDrpJWF4hL3jqzICUzusS0/cJ9726mr423iuGLBiwmvS5VK3a1lAkPXaN6VdW86CeSoiILxsI61ez8fXzuanU9foRukc2xvCCau+hZGA3kz2TWhhe2XW1ueOYN0AtIk0ZSibExPjYeYh+ut6q9VI1KbpbqKvLJFWJ1wMsHRGEgPG5r5U6Hj1bA0GcytW6Z/96wZUVJy3dbuRdZ3hf5kUoIr3pXtgkiroi0Bpag/DDLkVwCDYN+JqNCQlzgmRNg+IXgud82s7FxnYqak3H38loUwK+6xbftpC/RKxkudD46OHFf6zKvvkBWQNQNog5EVVedooOLGsghAevT60pNVVZzB/XS0IX/ZpCLl1i3mKYn//xhwQhDoGTjAMLoTnWyFirQDR+wm/P6iPPKGU9keFZIshbaadC6sZVDjhBPIpNPN2etv+CHEnE3ZLNKfFFaW1iTsV9FAh4Zt7nedz5/oAgQVaDwzitVt54Y86Siw5570w+MFeKk2bKzgBLDSkfig2lq2ogxFUJVgAzF8Usi6GR+9e3cidGT5dq2tkNIjYTjHE0ZGei+rBIhX85coGQAo1JWAT5PqzBJBKwAzqrnOhEElFzIG6bpOulWkyVQx+1idFrbKNnNEYkX3jTwHFtUwE/WdcOkuD7WOcnogVmR483GGuaD815mcZzlzsmtV078fth6HltTmel7d8vDtGUI0AN7akEew7QWAEvc1CD3P/JLjvb+txSTdLJSUNOo4GSOD/L/mijwWrK/dUfRvfHh+ctr5AY3o6kJeMTEX0gB3VISfCESLCRcaaQsdN+txx8PN1JN5+s99uZndQJaDHEzfuCOfv0ZAvreL9DMIlfTOq9Glw37i5rrfIjPV6ML9m7GozwYNAIGFzNkd2SkJICLav6HCURxx6Xt7z7652mR4yYZxjbbz5TZbtdkuYYOzo2sAQ9OMP4+/nCxeFLscF596luKaaDAlxqUF3ZGahQZtHoFESkL9GX8lLL3YNuPI4pe+cn/lQHMQT1KtP9TkT2Lc8NGl6PNE/Bg8K7k58a9Mnv0krIrf4m86+7RO98GcyoR0uUJ467x8MvHHQYADhcte2FqqVbL2blE/+jviRR0cIBv9InSu+kGchYm+p7k3zjtqEsQ4xpfd5eSfvzxknnetphXUKBQpYKIn/yVXMmlqDRdEUPQU5MEsdGAJbINXk5vc6imaUaTgYhI7vzYc81yXI96x6xn3Sa33I1t9vGuOBpWXVh7lRtz+usV1YNbYd4DOQRidNbCjmfV+W9oZZJqV5B1NsBwS+Df4EHf8F4T1jmByZRS7RYfQ3quilCXc8qxpul1I8EmqwCZHyyWdaPzWHIXLogUrXz7QzUgubBJllvaucA0kMCMFQLsVMYbP6YZJzueOUKmTjWFG9jQVdU1f5lhwHxvHOH76kVzeaJW2cUSkfRfg3B5maRHNwUdO5n6+pLi5VsBA/4CE/UqM8MY7E3lorUYZKAEex2ixXuG9e3PcQj8FauGa8BuEVAF6CqwB1xZx88NNWBpuBIipLQW0irgldOVf1P96D/DmmPChue4yrMoQSp0/BKZPGi0bR/EmEl+Ni6eqhzqgkfG4BNcNVHLUwNO0ERMwSaS1EiyAkQmdLUNsHZp/miHaOv+XW9WlR9abow3txacgxEsUOTSIjqKyKaGPTpjxCIH9Us5Myw4qnHoJC3GzGQbF2aEAwjFlwsizifKV7LGcn7qUpJ1wqjMbd2cM+CaKsx4f7fjvOwTb4SrNe8Og5AnhbUDmk5WdwJ0DTsPrOKTLirZFvlyXFwgGKCYlqaUACXt+Z/S5XmORDz2l7+lX7QAb3lyCxJFKW+pHRiEOqkqlwAg0bD5URkWKsh/QXENapNEq+x6hpkiAbd8431DlNQ+AxDn0oAK+3k5h31wAFwOQxnk+IDHvYu+36yU2fjD7gFgrplVhwc5oCFrFkV9deuAJ20/Uw0FxBFMv4yA9bKXKVpmVnK+T/bTZDJ/Fi6SQWx8U6dzAsNwTIs+oGoCOAIjnwm6NqPufFphPwaRvQH71Aq/cqc25mwLZUKB9Y75zIaQjrwhpLPPmHsaxQ/Pk91XsrfMRjuwC8sprU63K91MchfdEkFOWFJRvRzkCBAz7yY9alDvVpkrdX/PdzTzKB0pNlrGeZEAZs0/WdoEXr7AVmnO1Yjhcy+iPi31RqS2IYdWtggtsxVPPN2ZByilWS6z7jWoxklWoQzDAfWMPJWEDoIUacvYn4yhYihVOiz3b4qIsfTi6hWZb/JtVldFLpYuGkD9G5LZL0/br/eEmGswShZM3ERJ25iRG2utCBm7dLcSW6pr8Ak1+GjDsqRwfD4qASJ29LcXKyDR8jAw/7yrpffOHWHfx0ioF7FvXEzMXEPMT8eo13AdEiUhjjHQulO1ZQnleEHyBY+Gyy9fJjHBv99EfHUq3ZdpGxA2YwNqCoOKX8rymVb3Csf+rnyySs4CUKJd0OZIPXgiOQYqKr6UaXC7ULWid8bWTixv6WnsbbUkq24Ijo2Jv1L1g0ADO9B/V4WtUQvwL/8ixCHMR2OXpVyImeK1FgvyICe3ShZP9aufrh5i90EVvdavoy/23uAUtExXOduulXuVl3F+uSx1iH0QL+rP93DnjwD0bRauK0GT5ww5dd41n7OvTiDqeqs1eRSFrs1U4NVcSpbSP7deHfjGTckMBMJ9h2JpnCOiMkB6s9ubfsEIL29lsxOKcZ6LnoTUXnAFcYOVfby+u39HgZifriQZ0GZi9+v81uNbV3eyHR1SMDhPNkSQPfvHQzvDZMJ57jJ3lZ3Spa+a/oEM3Uuwa3eqUpcubzxGd59zMxD0kY+nReWMwoFrgk/zQB4N8t51vaSQFV793/Ld25Z/PxYfT+OCMfcp+r/iC0W3zK125ciugE8Z/FLXw5LY+BooA=
    key: AgAyc4LuXIa37/rvek7kTY6MV/W+8h74zwiWJOlK9X4aAmIBM0trddhVfn46PRYzt8mRvnC4e90+Pt1gmzmv//yDt4BOqA+YCTuSPCFI6++F0r6ffnvs9ECmRES5de+5UUH2uRkSOo7co6WHkXfizURiFc1khmNiMBQuCn4WUx9lWrYDKSHvr4IWEzcgOiK0SQQdD+4DtU/BWm1nGk6Jt5PIz5h4HsbT8akw5CVBh3fQsxaJ9UBLLvwQgPKrQVBc/khncPqb3TYmtnrKYcgMjXYQr0E3HEHGgwRyLCiz4MKfbRpeSXLnvzK1MhhgtTYfye4CCc+uQhvBFGQQB0opmqKEii+4ltlA5I5Xow+ZGE95NQtHEGY0aNdY2R78S5VIW3uu4IYJcA61wRr2w7YiMHPI1SYJ6FEDGZtL8YXcjGUS+iB3QZwNExNizfw93a7aNrGAfLQQD1JHFtF5b3Kg5toQKDcvr4g3jhtC/jEqAm6Bzs0UqmwfeewiDFVvyxyGlTSUCTqBp66T6SasDE33jfIhCtrwBzK6R4AEnepuWi/aRO1NntKlmPLLP/E9y5X2SUGMKkq2vbilYRK1AxhVcZz+ExlU4JNq3a2GUHFaqpfGO5T+hF/9YnB1+KHBbrsZ1U3zK7VAcpTDWDskZTBQO1rd2XieyrZnDC63J04AnKWYUYDjal2qvGXi2pk3tvVaFx/S3IdgmLox1mhu7Bt2OSH5YwaA19KJ8X/I6sGrw1tAA9pjZ7aSdwihwyODeCV5boFrJOndIZhKchzqwFR04w+9ustS1xF7FJZOvzdB8YXqEechcJIVZE5hh00psCMfUmt3zBmfS/kaY31w/aYgusEFCPq1QJx3sPohd9pMDazSgsN6yfgbU6TE7wlhdKSII9t5/6ntYP7Zkgt7I50VArIEVAblATOBpJjmQmmVr2FZZ6XrQCuWA77oxjM4C9mM+1pXOUFW55zo/uVswgKXGawSZcRUbem5ZyXQk6Q5nSfbOk2cn6mFPSQjycXOC0gGReQBV2qOxws1VPd3qP4NcdMfkEHul9Gk6WYmELug1z6/C0T2pchvvm4mEazi4NYQW3zqyXsHIJALfUaFv0pKS5BI9FKnNoSHUTavjocG6cTR42dCXxxQRTAZY1oAcjV5FPI7zDFyhQgWsY7BSUo2yNHv/LhSg0iaOthF8JUo/oHOKRP3RqqdubXIp4e4mPIkdbJCG6zqSeA/EBtwhL0eqIcT34mRgn9TuGk2rx8ZcfD+L+C/DHtZjtPexBqg2NtXgISEjxQHn7i6F/iey4ZkTDw8nEcQRRZLwkBZxq7+0IyX0+mS04gRKRpemGntcKpg5wWNlPwfnbAEpTm4WXgMfvSOKBYmVfnzhRRJa2VXA2MRtu5DcFY0VWEVv/TESJw6GRFfQ7aqgydnATcl5+cqFF4Rbi3vGFheFlWAPX+5Ps9s3mDybKtkDk9JZY0bSRxetQRdbcw/WJKEq0lIE6F7ev2pQX92Z4EXhwjdvpG1PPz+nTYjEtvS5XpQnw8g4Y7PZlvdLnWG7mri1Qej0gErgv0ssYBzyWWDZVnNIlDCgrKI0AK40fDNfRTtV6VjE1SK/1MycYSvloTaiMvNSGBh0cVWppxEoYlmVSY3hyIi2rVUYH+XLYK6iny0m33Oke/BdE//kptlGGiKsaSTp0zvYFCfIknZBhoJuzlvMqQajR3aNhCWaC+0a9sLWMtZz8jgI+QfzmSmylxzm1uEf26/AFaw0v0+c5ArS0pL2LT505xp39Qbm0UyjEQPGs/KltRuLd3tx4+jtESL8UQAj8WbqoHMsyE/c8km1eJ8MwcTaTJ3P2swhsGApbYhxa47ir1JtPhgXJSUf+WcnBAvoT6spsOpihe2NiLOPQ4LCEfd1etuQ6T3hxDEMIR7T9HWIyQqmN3wVQ2qRmgvkIE4KQNyBXdWxO05VN38FO/N9uVCeFCOkcsClHHh3heKEjqGizFCgiKj4qWDEODslBiGO7kauB68PvsTcrkD5ga17HdG+/LrdsLzppZiUFpJ5Wp3Xy06Cot7/SpCh9jo1eK3ZzYT2fc6IDzI+PDjashiqIVNhyeOu0mA/hgaHVBPawv4Z8x1lfj1zm6XR6iRc4ICIpN2mg9iG7aWXhIxbuEIcCRhmdE77Dp24g4FyV0ASu3TjiX3fCij76AF0Nn0SbCUwc+LCOwjzGMty+oFzo3LDxOjFTt6/Ifr+eqD80ir9ansMHo5ueru6Iq6eXGXO4osBiUScAITWAikMcbd6sjOOsD+rieil+I02a+TWvBqOAVCFweKX1Ojeh/Xul+6n6y6xkc1hCJnJkNLoOsdve0qHVk8MHBORRMYoYQqUYPaomCyxC4I8aHQC50QzT6IxsmovGqLf0BHrKm6VUjdEeqSmvci/HDl8Qp7HRuiartuwIjGcCBEHYsbYmBglvBJmsz1IArf9oRgPv36800S+jotdwPnl5oaM5B4yHBeqAbcI/4GljiY0O2v8MJfq53nv0IN852VQj3W/GCehqn7uu3FKgGbh3tRC0uefkFrbRrohvaVubgrlqRBXuaGqaZmPEuYBNZ6P8/jfxmX3BvSX1UX5bbKa1Br7lunHFAYMWY9hrzsBHHMOYVA1DQ4pLCTyq7K2VQW2EPT8CHMVN24nLnYO6YJlEauKAhin7r6D8XSkHpVjjfUeZpG2MpeZS4+s4J/KzZzxfimiMfjZXeGLOTR6RrJRDaFsMN6r0Llj1XK0DrfOSCS8c2y3DvEm/qw/pjnwaAQewk/qEgV9L5AB/9OxAqI6wlffyh3FF8m4zqNqazQa1vsupMBhv4dbaOiTcwpgQQ0trNFZ03525+wgdPjpGTbOIxM78thU3izYnJA9GKwf6+DCMZxVoDokCLVWy0Kk8r5rE6Qy+M1cERdSUKUzDprLK3tvhJ2+aFIcopJzW9fzybiPPHIEXCPqAk1mKfXb5jB9K1xopAdpA==
  appSecrets: 
    secretName: portfolio-webapp-env
    REACT_APP_EMAILJS_SERVICE_ID: AgCdgGWIiIB0BvpEBWYdl/Sbd9Bc0iV2MfjjaNQhJLFA+y3QxiskyxiwTJAXXN7NpciA5vqHKEr18fFaXNMkN9qsU9bg3Yo8N0VKsD4o4u5Hy5+bDWYPmCRzD6/EA2X8MI5mo2XAwmtzCPGDWEd++ADMpzcSI3t9a4gl+9OA8pLY639KmWtkkXrf/KYfFAslg+iCwlLCgX/eCe5h/gXz7nyrvu5RfdtHNTJuiXmLED74R2wUhLW1BYbuVd7fxwb7wRNNLUc7mDyxTQSOpgT4loRpisIvxIT9zF5SCtnCTI8e3j/+IFOlZdhMIUvnLA309/F1yAXzOGFFCbizktv64h2mDyHINnagVAudEpxsFIG2eVa9CjVEIq2d/v74Iuhk4QoNM0OHPvbSQeblrizuR56hi4DScn+DSZzF2D7L16OhLOTnoeH8zP8Sd9xugH/rSoIrsgG2wvq1P51sINSp96aR8OcngYlSfn36xNoJmeXnXvT1elUMqtqF8yMg9rbXgjUwWrRY+WsCCd26Sk+b6F4gWygTDAxFbtdqrGxACnb9QutpR17Jc4OTgLj95ljUjwlAVQLisq3HvTL26nxKrWQ5ckxLlAVTz3pOwVn3k4mLPCHZw53Bj/1Za+lA3UGO67slyVSnOm4PG7qnTXP7RenXd+Jrevfuw2y+W49uj63srcl0OIYQI6vOTdbG9r2R2JaLDw+ehFa6SmXlV5NplTs=
    REACT_APP_EMAILJS_TEMPLATE_ID: AgCWgz3GWQvW3m3tujfH82jroekuICMbsAx3+W9ob5/OT0YmrMslSJB7zlH+tI2Eixn9b5mqRW9R7WEnZceXjrQdTwCeNWCU9OyC7eGmqZ30xhT0hAC8M20mHjbSIg0gDDV1Vt9HOmY+qN3hvJb59LTO31JFtq85quKPIgAnnZvkKluW9iua02QorMdfg34GEZttG1wAvLu6bzdYBhawU53S3Q6YyGaSVqztAMrOMdOIRnT0cOe6zl09ztKZYoxC6e/4cfuJawwjyqrOI7rdVDLSa+yuc6JiKf1PJQRmXKaK1dbSaP7GXwgvKjVJCSnq3KL3PSRjSZWzSJKY2YC8AC1n4Di1EMEF3FlKlJ52LH/rTwqHI/pXNQNOD7tTEaU7m6Ke5HdsC1UUyPk5IZziRAK3V4Tf7IF7KabxjgGhNjUwSy00Wf31L0J4bhRuV6ML86exwzIwuMbb80YG6CAAB7mm6d956HA/6/IONXQqZR5jAV6NZ6W+e9u76acKuj6A0BgYFEqQNfubtBUqx0RA8rBuUJGTL5vb9Slphf2zzLbM0CgHPCQQAw7MPaM+kVETcFMmefM6494hMA+Ea8OJd8j/85fqfZeJINhYKlO/Zy6b6grWVnaJFVFcY8NO2cVHkKevGnx0dF91vlayDVhAkiQDJXbwnzI6w33E3yhQZEh4xH708I15UE7wag5rI3p2H24s03dEqzTTKCy6M4HyxhkC
    REACT_APP_EMAILJS_USER_ID: AgCfCMZMhXOBTbYxuQL1fmkMtsgfR/4AfcM9AaHec/0+NjzbYqAPe3MqGC/OhL5obxI55wndfOvyzmv64YBObFEJUWbiD2jk0eCpVdWerG6XWOcsoe/ez0A/16f1utvNY7+Z+CLBgyPeZoQjfoTWO+sE/+R3zNKIBLys+snywoglu3537JDY6748WOyopuA/6KxJVFVItovVbDUdJgGk6H88pEiXib4M8C2jCHoZUW/lxjeI5msHN0mGU1DQP9agEhml0l1E+Z07/LV0jbsR9m7U4xCOVkBH8prviBD2djB76ULmGEpyDTbWbyJyzpLMofikGIkgjtDNQW15jasEqSNw46Fl2akEeXJoVhX9OCjgjolI45sSFtx2LK/dLpLA8jAbMMs/aK5wY6n4Y/e7eX3oUizdWARm5ER8PqxQNqRJ5eql9qvzWFsbFoSc44b7ODQd6hU2CAdUf+p3jL5Q543fam2ObHvyptmKmDgnUvAEb8LI/Lhc9xHKn7uihPq1tbiSiigWNofhtnsdkGlm2v2Dq6NElDDv2fsyFeAm/q596z1cASRx7t9UJjrROS91sDtK5vQbCDr6AdiwIVQwYYGFoIvZExGbV07eZY3dlBG+GeX8MYOvpHABV8LW/qIXhZ+dvK/eC8/gSwvItJVK/q5e9vxoC02Muj8SQEiStxeHbPV2sgqNM27pY2anprgGyAW76Mo2+XD0VDiyR3oFJ1q0Gw==
  imagePullSecrets:
    secretName: image-pull-secret
    dockerconfigjson: AgBTu8qyoLOCYTus3deWfDdInyKxhAgDgBHVa7RenPAX6HMhVYXHW89Z8T9DcvyefsTpHj2PWqzTAAnxhslfi4ZteQiAKbps5Pqe3hHOgMmJs6H6J1fdlpGFU28RE7r9EgDMklnmL4SE7yBSvTawp6udNobGKy6nlqABFHfNsZ5QnZbNRcyaA5OHTFCGGMwEAHQ+HkCqjzCA3X9/o1m80Xsn4bWWx8A7uQFW47CbR7h8zGkqrVo60730tmN3MNHxaxldn72HuJZfd+kxKHTgal8KodGAVXbssYd/MZsIbfSvHhKD6Mo1W2oywjYoYcYyWKvpI6jnGg/Hr9ur2audY/YvY9B2MHTMct7Y9Z3Mv9YLJ6SUC8y67EhnTabNcOjOi+I3XWZWV+hjBhQIsSE8CPE6a2/Q+05F3+QXXzSvoqiDk2JwIh0AyzBIDi1q0zkykzHOQfx13XfUDGuUs6ucFSrezw8T4Zk2hK3QzdWGPd44asoGPzyggLEuhSnWmobYfOdz8UVx6cOodqrQ+KDXfmfgGurRlRfE0/x0As3PnGQDV0hBSEX28YbCL4WlWiCiQgVfLEBEoGH+WU9s00m3tH+sZdwzTS+pU2NxDXIwmmAnxagh7kg0dtL+yTTLCdX5KxPGzafSSWnAwwAFc6VVdD/51DVTT2EJSUNXCK7KSXrI5Tp9PKyKe+q4Z7Uf+naZCv62FfClY/hqNsY824BFNMCEwCxXMG3toeLYvhs0szKIHrk8OVBo7AhtJhA0nG4uWkZe1tW3wV6W2mSK+VqYHIukmTJaccjKtRYZQVfgscQr+SPmrtFENfLJc7n4OyY8qZ8LxrBRnx+flNWaiLGRXh32RDM=

image:
  repository: harbor.talrozen.com/portfolio/portfolio
  tag: "2.1.1"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  targetPort: 3000
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: talrozen.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: cloudflare-tls
     hosts:
       - talrozen.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
