{{- if eq .Release.Namespace .Values.sealedSecrets.encryptionNS -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecrets.tls.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    tls.crt: {{ .Values.sealedSecrets.tls.crt }}
    tls.key: {{ .Values.sealedSecrets.tls.key }}
  template:
    metadata:
      name: {{ .Values.sealedSecrets.tls.secretName }}
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/tls
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecrets.appSecrets.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    REACT_APP_EMAILJS_SERVICE_ID: {{ .Values.sealedSecrets.appSecrets.REACT_APP_EMAILJS_SERVICE_ID }}
    REACT_APP_EMAILJS_TEMPLATE_ID: {{ .Values.sealedSecrets.appSecrets.REACT_APP_EMAILJS_TEMPLATE_ID }}
    REACT_APP_EMAILJS_USER_ID: {{ .Values.sealedSecrets.appSecrets.REACT_APP_EMAILJS_USER_ID }}
  template:
    metadata:
      name: {{ .Values.sealedSecrets.appSecrets.secretName }}
      namespace: {{ .Release.Namespace }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecrets.imagePullSecrets.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.sealedSecrets.imagePullSecrets.dockerconfigjson }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.sealedSecrets.imagePullSecrets.secretName }}
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
{{- else }}
  {{- fail (printf "The namespace '%s' does not match the sealed secret encryption." .Release.Namespace) -}}
{{- end }}